version: "3.7"
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity-service
    ports:
      - "3307:3306"
    networks:
      - app-network

  phpmyadmin8-container:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container
    ports:
      - "8100:80"
    environment:
      PMA_HOST: mysql8-container
    networks:
      - app-network

  identity-spring-container:
    container_name: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8099:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-container:3306/identity-service?serverTimeZone=UTC&allowPublicKeyRetrieval=true
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_HOST: redis-container
      REDIS_PORT: 6379
      KAFKA_BROKER_SERVER: kafka-broker-01
      KAFKA_BROKER_PORT: 19092
    depends_on:
      - mysql8-container
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge


#docker-compose -f ./deployment.yml rm -s -f mysql8-container
#docker-compose -f ./deployment.yml up -d mysql8-container
#docker-compose -f ./deployment.yml up -d phpmyadmin8-container
#docker-compose -f ./deployment.yml up -d jenkins
